#pragma once

#include "types.h"

#include <filesystem>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

std::vector<LayerDef> loadManifest(const std::filesystem::path& root);

void loadLayerUiState(
    const std::filesystem::path& root,
    std::vector<LayerDef>& layers,
    bool& hover_inspector_enabled,
    int* hover_inspector_mode = nullptr,
    std::unordered_map<std::string, bool>* zoning_zone_enabled = nullptr,
    std::vector<bool>* layer_fill_enabled = nullptr,
    std::vector<bool>* layer_hover_enabled = nullptr,
    std::vector<bool>* layer_inspect_enabled = nullptr,
    std::vector<bool>* layer_heatmap_enabled = nullptr,
    std::vector<int>* layer_heatmap_max_zoom = nullptr,
    std::vector<int>* layer_parcel_detail_min_zoom = nullptr,
    std::vector<bool>* layer_heatmap_use_gradient = nullptr,
    std::vector<float>* layer_choropleth_gamma = nullptr,
    std::vector<int>* layer_heatmap_algo = nullptr,
    std::vector<int>* layer_normalize_mode = nullptr,
    std::vector<float>* layer_heatmap_cell_px = nullptr,
    std::vector<float>* layer_heatmap_bandwidth_px = nullptr,
    std::vector<float>* layer_heatmap_blur_sigma_px = nullptr,
    std::vector<float>* layer_heatmap_percentile_clip = nullptr,
    std::vector<bool>* layer_heatmap_zoom_adaptive_bandwidth = nullptr,
    std::vector<bool>* layer_heatmap_multires_enabled = nullptr,
    std::vector<float>* layer_heatmap_multires_blend = nullptr,
    int* heatmap_algo = nullptr,
    int* heatmap_quality_preset = nullptr,
    float* heatmap_cell_px = nullptr,
    float* heatmap_bandwidth_px = nullptr,
    float* heatmap_blur_sigma_px = nullptr,
    float* heatmap_percentile_clip = nullptr,
    bool* heatmap_zoom_adaptive_bandwidth = nullptr,
    bool* heatmap_multires_enabled = nullptr,
    float* heatmap_multires_blend = nullptr,
    bool* heatmap_allow_cpu_fallback = nullptr);

void saveLayerUiState(
    const std::filesystem::path& root,
    const std::vector<LayerDef>& layers,
    bool hover_inspector_enabled,
    const int* hover_inspector_mode = nullptr,
    const std::unordered_map<std::string, bool>* zoning_zone_enabled = nullptr,
    const std::vector<bool>* layer_fill_enabled = nullptr,
    const std::vector<bool>* layer_hover_enabled = nullptr,
    const std::vector<bool>* layer_inspect_enabled = nullptr,
    const std::vector<bool>* layer_heatmap_enabled = nullptr,
    const std::vector<int>* layer_heatmap_max_zoom = nullptr,
    const std::vector<int>* layer_parcel_detail_min_zoom = nullptr,
    const std::vector<bool>* layer_heatmap_use_gradient = nullptr,
    const std::vector<float>* layer_choropleth_gamma = nullptr,
    const std::vector<int>* layer_heatmap_algo = nullptr,
    const std::vector<int>* layer_normalize_mode = nullptr,
    const std::vector<float>* layer_heatmap_cell_px = nullptr,
    const std::vector<float>* layer_heatmap_bandwidth_px = nullptr,
    const std::vector<float>* layer_heatmap_blur_sigma_px = nullptr,
    const std::vector<float>* layer_heatmap_percentile_clip = nullptr,
    const std::vector<bool>* layer_heatmap_zoom_adaptive_bandwidth = nullptr,
    const std::vector<bool>* layer_heatmap_multires_enabled = nullptr,
    const std::vector<float>* layer_heatmap_multires_blend = nullptr,
    const int* heatmap_algo = nullptr,
    const int* heatmap_quality_preset = nullptr,
    const float* heatmap_cell_px = nullptr,
    const float* heatmap_bandwidth_px = nullptr,
    const float* heatmap_blur_sigma_px = nullptr,
    const float* heatmap_percentile_clip = nullptr,
    const bool* heatmap_zoom_adaptive_bandwidth = nullptr,
    const bool* heatmap_multires_enabled = nullptr,
    const float* heatmap_multires_blend = nullptr,
    const bool* heatmap_allow_cpu_fallback = nullptr);

void loadFilterUiState(
    const std::filesystem::path& root,
    bool* filter_enabled = nullptr,
    bool* filter_use_date = nullptr,
    int* filter_year_min = nullptr,
    int* filter_year_max = nullptr,
    char* filter_blocklot = nullptr,
    size_t filter_blocklot_size = 0,
    char* filter_status = nullptr,
    size_t filter_status_size = 0,
    char* filter_address = nullptr,
    size_t filter_address_size = 0,
    char* filter_owner = nullptr,
    size_t filter_owner_size = 0,
    char* filter_zip = nullptr,
    size_t filter_zip_size = 0,
    bool* crime_filter_enabled = nullptr,
    bool* crime_filter_homicide = nullptr,
    bool* crime_filter_robbery = nullptr,
    bool* crime_filter_assault = nullptr,
    bool* crime_filter_burglary = nullptr,
    bool* crime_filter_theft = nullptr,
    bool* crime_filter_auto_theft = nullptr,
    bool* crime_filter_drug = nullptr,
    bool* crime_filter_shooting = nullptr,
    bool* crime_filter_use_year = nullptr,
    int* crime_year_min = nullptr,
    int* crime_year_max = nullptr,
    char* owner_search_query = nullptr,
    size_t owner_search_query_size = 0,
    std::unordered_set<std::string>* selected_owners = nullptr);

void saveFilterUiState(
    const std::filesystem::path& root,
    bool filter_enabled,
    bool filter_use_date,
    int filter_year_min,
    int filter_year_max,
    const char* filter_blocklot,
    const char* filter_status,
    const char* filter_address,
    const char* filter_owner,
    const char* filter_zip,
    bool crime_filter_enabled,
    bool crime_filter_homicide,
    bool crime_filter_robbery,
    bool crime_filter_assault,
    bool crime_filter_burglary,
    bool crime_filter_theft,
    bool crime_filter_auto_theft,
    bool crime_filter_drug,
    bool crime_filter_shooting,
    bool crime_filter_use_year,
    int crime_year_min,
    int crime_year_max,
    const char* owner_search_query,
    const std::unordered_set<std::string>& selected_owners);

void loadMapUiState(
    const std::filesystem::path& root,
    double* center_lon = nullptr,
    double* center_lat = nullptr,
    int* zoom = nullptr,
    size_t* selected_parcel_idx = nullptr,
    std::vector<size_t>* selected_parcel_indices = nullptr);

void saveMapUiState(
    const std::filesystem::path& root,
    double center_lon,
    double center_lat,
    int zoom,
    size_t selected_parcel_idx,
    const std::vector<size_t>& selected_parcel_indices);
