#pragma once

#include <filesystem>
#include <string>

struct WorldsimCliOptions {
    bool show_help = false;
    bool run_vacancy_selftest = false;
    bool run_projection_cache_selftest = false;
    bool run_projection_fill_cache_selftest = false;
    bool run_projection_color_cache_selftest = false;
    bool run_polygon_hole_selftest = false;
    bool run_spatial_index_selftest = false;
    bool run_layer_profile_selftest = false;
    bool run_layer_runtime_status_selftest = false;
    bool run_parcel_gpu_cpu_bypass_selftest = false;
    bool run_vulkan_device_loss_selftest = false;
    bool run_render_routing_selftest = false;
    bool run_render_tile_cache_selftest = false;
    bool run_render_polygon_tile_runtime_policy_selftest = false;
    bool run_render_policy_selftest = false;
    bool run_render_plan_selftest = false;
    bool run_canonical_parcel_binary_selftest = false;
    bool run_parcel_polygon_identity_selftest = false;
    bool run_polygon_artifact_resilience_selftest = false;
    bool run_parcel_polygon_feature_idx_selftest = false;
    bool run_parcel_hover_click_pick_selftest = false;
    bool run_parcel_selection_ui_harness = false;
    bool run_parcel_hover_click_ui_harness = false;
    bool run_verify_parcel_duckdb_keys = false;
    bool run_duckdb_parcel_semantic_snapshot_selftest = false;
    bool run_duckdb_parcel_ingest_selftest = false;
    bool run_population_metrics_selftest = false;
    bool run_beps_screening_selftest = false;
    bool run_inspect_canonical_parcel_binary = false;
    bool run_validate_canonical_parcel_binary = false;
    bool run_parcel_artifact_health = false;
    bool run_compile_point_geometry = false;
    bool run_validate_point_geometry = false;
    bool run_compile_polyline_geometry = false;
    bool run_validate_polyline_geometry = false;
    bool run_compile_polygon_geometry = false;
    bool run_compile_parcel_polygon_geometry_artifacts = false;
    bool run_validate_polygon_geometry = false;
    bool run_render_polygon_tile = false;
    bool run_build_geometry_duckdb_artifacts = false;
    bool run_startup_preprocess = false;
    bool rebuild_all_artifacts_from_scratch = false;
    bool run_download_layers = false;
    bool run_generate_canonical_files = false;
    bool run_rebuild_duckdb_analytics = false;
    bool run_inspect_duckdb_geography_tables = false;
    bool run_report_duckdb_coverage = false;
    bool run_build_parcel_matched_layers = false;
    bool run_build_parcel_zone_memberships = false;
    bool run_build_population_metrics = false;
    bool run_build_beps_candidates = false;
    bool force_build_parcel_matched_layers = false;
    bool run_color_editor = false;
    bool debug_gpu_aggregate = false;
    bool include_large_downloads = false;
    int reserve_cores = 0;
    bool reserve_cores_set = false;
    std::string download_phase;
    std::string generate_canonical_phase;
    std::string canonical_parcel_binary_file;
    std::string point_geometry_file;
    std::string polyline_geometry_file;
    std::string polygon_geometry_file;
    std::string render_polygon_tile_file;
    std::string parcel_zone_membership_zone_layer_file;
    int render_tile_z = -1;
    int render_tile_x = -1;
    int render_tile_y = -1;
    std::string color_editor_session_file;
};

WorldsimCliOptions parseWorldsimCliOptions(int argc, char** argv);
int runWorldsimCliImmediate(const std::filesystem::path& root, const WorldsimCliOptions& options);
void printWorldsimUsage();
